---
Author: Gábor Szalai
Version: 1551-CNL 113 660, Rev. A
Date: 2013-09-05

---
= IMAP 4rev1  Protocol Modules for TTCN-3 Toolset with Titan, Description
:author: Gábor Szalai
:revnumber: 1551-CNL 113 660, Rev. A
:revdate: 2013-09-05
:toc:

= Functionality

The IMAP 4rev1 protocol module implements the message structures of the related protocol <<_4, [4]>> in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

The IMAP 4rev1 protocol module uses Titan’s TEXT encoding attributes <<_3, [3]>> and hence is usable with the Titan test toolset only.

== Implemented Protocols

This set of protocol modules implements protocol messages and constants of the IMAP protocol as described in <<_4, [4]>>. All of the IMAP commands, responses and greetings defined in <<_4, [4]>> are implemented.

=== Modified and Non-Implemented Protocol Elements

The following rules of <<_4, [4]>> are simplified to charstrings: "msg-att", "mbx-list-flags", "list-mailbox".

The rule "flag" of <<_4, [4]>> is handled as a restricted charstring.

=== Ericsson-Specific Changes

None.

== Backward Incompatibilities

None.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

Titan TTCN-3 Test Executor version CRL 113 200 R7A (1.7.pl0) or higher installed. For Installation Guide see <<_2, [2]>>. Please note: This version of the test port is not compatible with Titan releases earlier than CRL 113 200 R7A.

= Usage

== Installation

The set of protocol modules can be used in developing TTCN-3 test suites using any text editor; however, to make the work more efficient a TTCN3enabled text editor is recommended (for example, nedit, xemacs). Since the IMAP 4rev1 protocol is used as a part of a TTCN-3 test suite, this requires TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<_2, [2]>>.

== Configuration

None.

== Message Dissection Function for IPL4 Test Port

The protocol module provides base function for message dissection:

[source]
external function IMAP_get_msg_length(in octetstring stream, in boolean client_side:=true) return integer

The function returns the length of the first complete message in the stream buffer or `_-1_` if the buffer contains only incomplete message.

In client side, the function takes into account the literals, so the length of the whole message returned.

In server side, the literals should not be taken into account, because the server should prepare a buffer to hold the literal. See section 7.5 of <<_5, [5]>>. The message boundary calculated by the position of the first CRLF, so the reception of the literals should be handled by the test case code.

== Examples

None.

= Interface Description

== Top Level PDU

The top level PDUs are the TTCN-3 records `IMAP_ClientCommand`, `IMAP_ServerResponse`, and `IMAP_ServerResponse_separated`.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions, which assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan.

=== Implemented Encoding and Decoding Functions

Encoder functions for charstring format:

[source]
----
external function textenc_IMAP_PDU(in IMAP_PDU pdu) return charstring

external function textdec_IMAP_Command(in charstring stream) return IMAP_ClientCommand

external function textdec_IMAP_Response(in charstring stream) return IMAP_ServerResponse

external function textdec_IMAP_Response_separated(in charstring stream) return IMAP_ServerResponse_separated
----

Encoder functions for octetstring format:

[source]
----
external function octenc_IMAP_PDU(in IMAP_PDU pdu) return octetstring

external function octdec_IMAP_Command(in octetstring stream) return IMAP_ClientCommand

external function octdec_IMAP_Response(in octetstring stream) return IMAP_ServerResponse

external function octdec_IMAP_Response_separated(in octetstring stream) return IMAP_ServerResponse_separated
----

= Terminology

== Abbreviations

PDU:: Protocol Data Unit

IMAP:: Internet Message Access Protocol - Version 4rev1

TTCN-3:: Testing and Test Control Notation version 3

= References

[[_1]]
[1] ETSI ES 201 873-1 v4.4.1 (2012-04) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_2]]
[2] User Guide for TITAN TTCN-3 Test Executor

[[_3]]
[3] Programmer’s Technical Reference for Titan TTCN–3 Test Executor

[[_4]]
[4] IMAP 4rev1 Protocol Modules for TTCN-3 Toolset with Titan
Product Revision Information

[[_5]]
[5] https://tools.ietf.org/html/rfc3501[RFC3501] +
INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1

